In [21]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

In [3]:
data=pd.read_csv('diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [11]:
data_n=data.iloc[:,:-1]
data_new=np.array(data_n)
data_new

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [13]:
covMat=pd.DataFrame(data=np.cov(data_new,rowvar=False))
covMat

0            1           2           3             4           5  \
0  11.354056    13.947131    9.214538   -4.390041    -28.555231    0.469774   
1  13.947131  1022.248314   94.430956   29.239183   1220.935799   55.726987   
2   9.214538    94.430956  374.647271   64.029396    198.378412   43.004695   
3  -4.390041    29.239183   64.029396  254.473245    802.979941   49.373869   
4 -28.555231  1220.935799  198.378412  802.979941  13281.180078  179.775172   
5   0.469774    55.726987   43.004695   49.373869    179.775172   62.159984   
6  -0.037426     1.454875    0.264638    0.972136      7.066681    0.367405   
7  21.570620    99.082805   54.523453  -21.381023    -57.143290    3.360330   

          6           7  
0 -0.037426   21.570620  
1  1.454875   99.082805  
2  0.264638   54.523453  
3  0.972136  -21.381023  
4  7.066681  -57.143290  
5  0.367405    3.360330  
6  0.109779    0.130772  
7  0.130772  138.303046

In [14]:
eignV, eignVe=np.linalg.eig(covMat)

In [15]:
eignV

array([1.34565730e+04, 9.32760132e+02, 3.90577831e+02, 1.98182691e+02,
       1.12689115e+02, 4.58294431e+01, 7.76070899e+00, 1.02871018e-01])

In [16]:
eignVe

array([[-2.02176587e-03,  2.26488861e-02, -2.24649003e-02,
        -4.90459604e-02, -1.51612874e-01, -5.04730888e-03,
         9.86672995e-01, -6.10123250e-03],
       [ 9.78115765e-02,  9.72210040e-01,  1.43428710e-01,
         1.19830016e-01,  8.79407680e-02,  5.07391813e-02,
         8.83426114e-04,  8.25459539e-04],
       [ 1.60930503e-02,  1.41909330e-01, -9.22467192e-01,
        -2.62742788e-01,  2.32165009e-01,  7.56365525e-02,
        -1.22975947e-03, -5.20865450e-04],
       [ 6.07566861e-02, -5.78614699e-02, -3.07013055e-01,
         8.84369380e-01, -2.59973487e-01,  2.21363068e-01,
        -3.76444746e-04,  2.54871909e-03],
       [ 9.93110844e-01, -9.46266913e-02,  2.09773019e-02,
        -6.55503615e-02,  1.72312241e-04, -6.13326472e-03,
         1.42307394e-03,  2.68965921e-04],
       [ 1.40108085e-02,  4.69729766e-02, -1.32444542e-01,
         1.92801728e-01, -2.14744823e-02, -9.70776708e-01,
        -2.73046214e-03,  2.67341863e-03],
       [ 5.37167919e-04,  8.168046

In [55]:
totalSum=sum(eignV)
percent=[(i/totalSum)for i in sorted(eignV,reverse=True)]
percent

[0.888546634575624,
 0.06159078374587651,
 0.025790118917661545,
 0.013086137415140801,
 0.007440938639887567,
 0.0030261491882255707,
 0.0005124448745698516,
 6.79264301407264e-06]

In [47]:
pca4c=eignVe[:,:4]
pca4c

array([[-2.02176587e-03,  2.26488861e-02, -2.24649003e-02,
        -4.90459604e-02],
       [ 9.78115765e-02,  9.72210040e-01,  1.43428710e-01,
         1.19830016e-01],
       [ 1.60930503e-02,  1.41909330e-01, -9.22467192e-01,
        -2.62742788e-01],
       [ 6.07566861e-02, -5.78614699e-02, -3.07013055e-01,
         8.84369380e-01],
       [ 9.93110844e-01, -9.46266913e-02,  2.09773019e-02,
        -6.55503615e-02],
       [ 1.40108085e-02,  4.69729766e-02, -1.32444542e-01,
         1.92801728e-01],
       [ 5.37167919e-04,  8.16804621e-04, -6.39983017e-04,
         2.69908637e-03],
       [-3.56474430e-03,  1.40168181e-01, -1.25454310e-01,
        -3.01024330e-01]])

In [48]:
pca4cT=np.transpose(pca4c)
dataT=np.transpose(data_new)
newdata=np.matmul(pca4cT,dataT)
newDataSet=np.transpose(newdata)
newDataSet

array([[ 18.04202911, 160.80251286, -66.79368843,  20.90462808],
       [ 11.39841643,  95.943517  , -65.02957086,  14.23991254],
       [ 19.12604059, 192.75822668, -40.07109135,  -0.41769765],
       ...,
       [125.86988229, 121.47506542, -61.12076394,   4.35691332],
       [ 13.54218971, 139.03774998, -47.18163558,  -9.05890071],
       [ 12.4485343 , 103.23023416, -67.6856678 ,  19.05706431]])

In [49]:
x=newDataSet
y=data.iloc[:,8]

In [50]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [51]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [52]:
y_predict=dtc.predict(x_test)

In [53]:
accuracy_score(y_test,y_predict)

0.6493506493506493

In [54]:
confusion_matrix(y_test,y_predict)

array([[109,  45],
       [ 36,  41]], dtype=int64)